[package]
name = "crates-and-packages"
version = "0.1.0"
authors = ["C1296135 Eduardo Soares Sampaio <eduardo.ssampaio@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
